# log_level = "debug"
log_level = "quiet"

[rocklet]
name = "todolint"
identifier = "com.github.mcandre.todolint"
rev = "1"
maintainer = "Andrew Pennebaker <n4jm4@pm.me>"
manufacturer = "YelloSoft"
summary = "code comment SAST security scanner"
description = "todolint identifies bugs based on code comments"
copyright = "Copyright (C) 2025 Andrew Pennebaker"
license = "0BSD"
url = "https://github.com/mcandre/todolint"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-macos"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
dest."usr/local/bin" = ".crit/bin/todolint/x86_64-apple-darwin"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-macos"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
dest."usr/local/bin" = ".crit/bin/todolint/aarch64-apple-darwin"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-ubuntu"
rocklet.oci_arch = "linux/amd64"
dest."usr/bin" = ".crit/bin/todolint/x86_64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:0.0.23-ubuntu"
rocklet.oci_arch = "linux/arm64"
dest."usr/bin" = ".crit/bin/todolint/aarch64-unknown-linux-musl"
